const text = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae nisl neque. Cras at nulla in ante porttitor pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur iaculis mauris a lectus sagittis luctus non et metus. Proin et diam ex. Donec ac laoreet ligula. Duis mi nisl, ornare a tincidunt a, sollicitudin vitae velit. Donec facilisis tempor congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Mauris at dictum tortor, gravida dignissim risus. Maecenas pulvinar quam ut eleifend consequat. Sed vitae dignissim risus. Vivamus volutpat nisi id mauris molestie, in rhoncus felis faucibus. Morbi iaculis mi eget ultrices ultricies. Pellentesque nec varius diam. Vivamus ornare sapien id ultricies rhoncus.

Aliquam pretium leo justo, sit amet faucibus erat interdum et. Aenean varius volutpat pellentesque. Sed molestie maximus tempus. Pellentesque interdum quis enim eu ultrices. Aliquam a venenatis orci. Quisque ipsum dolor, pretium tristique sodales sed, varius eu elit. Ut sed interdum erat, nec fermentum purus. Sed sem risus, gravida commodo sodales vitae, consequat eu justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec diam nec felis cursus tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean sed est ut orci lobortis blandit. Vivamus metus augue, pretium eget lorem eu, blandit tincidunt arcu. Mauris non efficitur turpis.

Ut scelerisque purus non orci elementum, a consequat velit pulvinar. Nam dapibus sed arcu luctus tempor. Nam sed lorem mollis, tempus leo a, ultricies turpis. Morbi posuere maximus eros, id pharetra lectus efficitur non. Proin nec lacus dolor. Mauris condimentum odio eros, eu volutpat arcu maximus vitae. Donec ac eros in tortor rhoncus laoreet non sit amet nulla. In aliquet eros a purus semper, ut porta dui fringilla. Mauris pretium massa quam, sit amet efficitur lorem consequat consequat. Duis euismod viverra justo, scelerisque lobortis eros mattis ac.

Curabitur dui odio, facilisis non diam vel, scelerisque volutpat nibh. Aliquam scelerisque sit amet lorem at accumsan. Maecenas et fringilla nisi. Quisque efficitur convallis neque, eu vehicula nisl dapibus ac. Morbi ac mauris eget ligula consequat dictum. Donec quis risus vel mauris iaculis convallis. Aenean egestas eros id eros scelerisque efficitur. Donec euismod est vel nisi mattis pharetra. Nullam mollis enim eget hendrerit ornare. Vivamus aliquam metus sit amet ante egestas, non aliquam augue blandit. Vestibulum gravida, ante nec fringilla sagittis, nibh turpis suscipit nibh, ut accumsan nulla tortor ultrices libero.
`;

export default text;
